import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { existsSync, mkdirSync, copyFileSync, writeFileSync } from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source is under src/. See https://github.com/Taverntop-Games-Software/taverntop-obsidian
*/`;

const production = process.argv[2] === "production";

// Local dev loop: set TTOP_DEV_VAULT to an Obsidian vault path and `npm run dev` builds
// straight into <vault>/.obsidian/plugins/taverntop-sync/, copies manifest.json + styles.css,
// and touches `.hotreload` so the "Hot Reload" community plugin reloads on each rebuild.
// Unset (or in production) → behaves as before: emits main.js at the repo root.
const devVault = production ? undefined : process.env.TTOP_DEV_VAULT;
const pluginDir = devVault
  ? path.join(devVault, ".obsidian", "plugins", "taverntop-sync")
  : null;
if (pluginDir && !existsSync(pluginDir)) mkdirSync(pluginDir, { recursive: true });
const outfile = pluginDir ? path.join(pluginDir, "main.js") : "main.js";

// esbuild plugin: after each dev rebuild, mirror the static assets into the vault + poke Hot Reload.
const syncVaultAssets = {
  name: "sync-vault-assets",
  setup(build) {
    build.onEnd((result) => {
      if (!pluginDir || result.errors.length) return;
      for (const f of ["manifest.json", "styles.css"]) {
        try { copyFileSync(f, path.join(pluginDir, f)); } catch { /* asset optional */ }
      }
      try { writeFileSync(path.join(pluginDir, ".hotreload"), ""); } catch { /* Hot Reload optional */ }
      console.log(`[dev] built into ${pluginDir}`);
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  // `obsidian` and Electron/CodeMirror internals are provided by the host at runtime.
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile,
  minify: production,
  plugins: pluginDir ? [syncVaultAssets] : [],
});

if (production) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
