import { Adventure, CanonEntity, GameSession } from "../model/canon";

/**
 * Fixture canon drawn from the two real reference fixtures in the spec
 * (Appendix A "Aftermath" adventure; Appendix B Campaign 2 scaffold). Lets us
 * exercise push+pull, wikilink round-tripping, and dm_only handling with no backend.
 */

const TENANT = "2004";
const C2 = "c2";

export const FIXTURE_CANON: CanonEntity[] = [
  {
    id: "npc-0001",
    type: "npc",
    tenantId: TENANT,
    campaignId: C2,
    canonStatus: "confirmed",
    viability: "live",
    origin: "recapped",
    visibility: "player",
    name: "Thoren",
    title: "The Vault-Touched",
    pronouns: "he/him",
    oneLine: "Back from the Vault and dangerously interested in Malrik.",
    description: "A scholar of the Spine whose curiosity outruns his caution.",
    lifeStatus: "alive",
    disposition: "friendly",
    createdUtc: "2026-06-20T18:00:00Z",
    updatedUtc: "2026-06-28T18:00:00Z",
    dmOnly: [
      { facet: "secret", value: "After the Yith Illusk mind-meld he is fracturing into multiple personalities." },
      { facet: "want", value: "To understand the Vault's time mechanics — whatever it costs the party." },
    ],
    links: [
      { linkType: "found_at", toType: "location", toId: "loc-0002", toName: "The Vault" },
      { linkType: "involves", toType: "thread", toId: "thr-0001", toName: "The Destabilizing Portal" },
    ],
  },
  {
    id: "npc-0002",
    type: "npc",
    tenantId: TENANT,
    campaignId: C2,
    canonStatus: "confirmed",
    viability: "live",
    origin: "recapped",
    visibility: "dm_only",
    name: "The Faceless Broker",
    title: "Trader in Stolen Faces",
    pronouns: "they/them",
    oneLine: "A Faceless agent who deals in identities torn from Tethertown.",
    lifeStatus: "alive",
    disposition: "varies",
    createdUtc: "2026-06-21T18:00:00Z",
    updatedUtc: "2026-06-27T18:00:00Z",
    dmOnly: [
      { facet: "secret", value: "Is itself a fragment Morosyth once devoured; fears the Vanguard holds another." },
    ],
    links: [
      { linkType: "member_of", toType: "faction", toId: "fac-faceless", toName: "The Faceless" },
      { linkType: "involves", toType: "thread", toId: "thr-0002", toName: "Who Is Tearing Pieces Out of Tethertown" },
    ],
  },
  {
    id: "loc-0001",
    type: "location",
    tenantId: TENANT,
    campaignId: C2,
    canonStatus: "confirmed",
    viability: "live",
    origin: "imported",
    visibility: "player",
    name: "Tethertown",
    kind: "settlement",
    oneLine: "A patchwork district of Sigil that is quietly coming apart.",
    placeStatus: "active",
    createdUtc: "2026-06-15T18:00:00Z",
    updatedUtc: "2026-06-15T18:00:00Z",
    dmOnly: [],
    links: [{ linkType: "controlled_by", toType: "faction", toId: "fac-faceless", toName: "The Faceless" }],
  },
  {
    id: "loc-0002",
    type: "location",
    tenantId: TENANT,
    campaignId: C2,
    canonStatus: "confirmed",
    viability: "live",
    origin: "recapped",
    visibility: "player",
    name: "The Vault",
    kind: "dungeon",
    parentLocationId: "loc-0001",
    oneLine: "A time-anchored vault whose stolen artifact is unmaking the portal.",
    placeStatus: "active",
    createdUtc: "2026-06-22T18:00:00Z",
    updatedUtc: "2026-06-28T18:00:00Z",
    dmOnly: [{ facet: "secret", value: "Removing the artifact cost the vault its temporal anchor — this is the feedback loop." }],
    links: [],
  },
  {
    id: "thr-0001",
    type: "thread",
    tenantId: TENANT,
    campaignId: C2,
    canonStatus: "confirmed",
    viability: "live",
    origin: "recapped",
    visibility: "player",
    name: "The Destabilizing Portal",
    oneLine: "The Spine's portal is tearing itself apart.",
    currentState: "The party knows the Vault artifact is the cause; the anchor is failing.",
    threadStatus: "active",
    tract: "Main",
    createdUtc: "2026-06-22T18:00:00Z",
    updatedUtc: "2026-06-28T18:00:00Z",
    dmOnly: [],
    links: [
      { linkType: "involves", toType: "location", toId: "loc-0002", toName: "The Vault" },
      { linkType: "involves", toType: "npc", toId: "npc-0001", toName: "Thoren" },
    ],
  },
  {
    id: "thr-0002",
    type: "thread",
    tenantId: TENANT,
    campaignId: C2,
    canonStatus: "confirmed",
    viability: "live",
    origin: "recapped",
    visibility: "dm_only",
    name: "Who Is Tearing Pieces Out of Tethertown",
    oneLine: "Someone is extracting 'pieces' of Tethertown to rebuild a lost realm.",
    currentState: "Seeded; the party has not yet connected the disappearances to the Faceless.",
    threadStatus: "seeded",
    tract: "Main",
    createdUtc: "2026-06-16T18:00:00Z",
    updatedUtc: "2026-06-25T18:00:00Z",
    dmOnly: [{ facet: "truth", value: "The Faceless are rebuilding their devoured home plane, piece by piece." }],
    links: [{ linkType: "involves", toType: "location", toId: "loc-0001", toName: "Tethertown" }],
  },
  {
    id: "hok-0001",
    type: "hook",
    tenantId: TENANT,
    campaignId: null,
    canonStatus: "provisional",
    viability: "live",
    origin: "recapped",
    visibility: "player",
    name: "The Missing Caravan Bryn Swore to Find",
    oneLine: "A supply caravan vanished on the Slop Street road; Bryn wants it found.",
    context: "Left dangling after last month's session; no DM has claimed it.",
    hookStatus: "open",
    leftByUserId: "user-sarah",
    heat: "hot",
    createdUtc: "2026-06-10T18:00:00Z",
    updatedUtc: "2026-06-10T18:00:00Z",
    dmOnly: [],
    links: [{ linkType: "references", toType: "location", toId: "loc-0001", toName: "Tethertown" }],
  },
  {
    id: "lor-0001",
    type: "lore",
    tenantId: TENANT,
    campaignId: C2,
    canonStatus: "confirmed",
    viability: "live",
    origin: "imported",
    visibility: "player",
    name: "Narakshar's Ascension Rite",
    body: "The rite that made Narakshar a god created a reusable cosmic template — the seed the Cult of the One would later misread.",
    category: "cosmology",
    tags: ["cosmology", "cult-of-the-one", "narakshar"],
    createdUtc: "2026-06-16T18:00:00Z",
    updatedUtc: "2026-06-16T18:00:00Z",
    dmOnly: [],
    links: [{ linkType: "about", toType: "faction", toId: "fac-cult", toName: "Cult of the One" }],
  },
  {
    id: "rum-0001",
    type: "rumor",
    tenantId: TENANT,
    campaignId: C2,
    canonStatus: "provisional",
    viability: "live",
    origin: "manual",
    visibility: "player",
    name: "The Vault Runs Backwards at Night",
    oneLine: "Tavern talk says clocks near the Spine tick backwards after dark.",
    plantedByRole: "player",
    veracity: "partial",
    createdUtc: "2026-06-24T18:00:00Z",
    updatedUtc: "2026-06-24T18:00:00Z",
    dmOnly: [{ facet: "truth", value: "Not backwards — the failing anchor is bleeding small time-bubbles into the district." }],
    links: [{ linkType: "about", toType: "location", toId: "loc-0002", toName: "The Vault" }],
  },
];

export const FIXTURE_ADVENTURES: Adventure[] = [
  {
    id: "adv-0001",
    tenantId: TENANT,
    campaignId: C2,
    title: "The Lost Origin",
    code: "A1P3",
    teaser: "The party follows the portal's failure into the Vault — and into the Faceless' grief.",
    dungeonMasterName: "Mike",
    sessionId: "ses-0001",
    updatedUtc: "2026-06-28T18:00:00Z",
    acts: [
      {
        title: "Act 1 — Setup",
        timebox: "15m",
        beats: [
          {
            kind: "strong_start",
            title: "Strong Start",
            body: "Open on Valas, bloodied, holding the containment perimeter against portal remnants.",
            canonRefs: [{ type: "location", id: "loc-0001", name: "Tethertown" }],
          },
          {
            kind: "npc",
            title: "Introduce the NPCs",
            body: "Thoren is back from the Vault and fixated on Malrik's cloak.",
            canonRefs: [{ type: "npc", id: "npc-0001", name: "Thoren" }],
          },
        ],
      },
      {
        title: "Act 2 — Confrontation",
        timebox: "45m–1hr",
        beats: [
          {
            kind: "scene",
            title: "The Ritual Site",
            body: "Explore the portal and bodies for clues; the portal is destabilizing.",
            canonRefs: [
              { type: "location", id: "loc-0002", name: "The Vault" },
              { type: "thread", id: "thr-0001", name: "The Destabilizing Portal" },
            ],
          },
        ],
      },
      {
        title: "Act 3 — Resolution",
        timebox: "45m–1hr",
        beats: [
          {
            kind: "set_piece",
            title: "Control the Flow of Time",
            body: "Thoren + the Yith Illusk mind-meld to open a small time bubble. Removing the artifact cost the vault its anchor.",
            canonRefs: [{ type: "location", id: "loc-0002", name: "The Vault" }],
          },
        ],
      },
    ],
  },
];

export const FIXTURE_SESSIONS: GameSession[] = [
  {
    id: "ses-0001",
    tenantId: TENANT,
    campaignId: C2,
    title: "Game Night — The Lost Origin",
    date: "2026-07-01",
    adventureIds: ["adv-0001"],
    updatedUtc: "2026-06-28T18:00:00Z",
  },
];
